import PDFDocument from "pdfkit";

// Converts PRD markdown content to a PDF Buffer
export function generatePrdPdf(content, version, projectName = "Proyek") {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header bar
    doc.rect(0, 0, doc.page.width, 60).fill("#2C2F33");
    doc.fillColor("#FFFFFF").fontSize(18).font("Helvetica-Bold")
      .text("FreeWANcer", 50, 18);
    doc.fontSize(10).font("Helvetica")
      .text(`Project Requirements Document — v${version}`, 50, 40);
    doc.fillColor("#000000").moveDown(2);

    renderMarkdown(doc, content);

    // Footer
    const bottom = doc.page.height - 40;
    doc.fontSize(8).fillColor("#888888")
      .text(`Generated by FreeWANcer Bot • PRD v${version} • ${new Date().toLocaleDateString("id-ID")}`, 50, bottom, {
        align: "center",
        width: doc.page.width - 100,
      });

    doc.end();
  });
}

function renderMarkdown(doc, text) {
  const lines = text.split("\n");
  let inTable = false;

  for (const raw of lines) {
    const line = raw.trimEnd();

    // Horizontal rule
    if (/^---+$/.test(line)) {
      doc.moveDown(0.3)
        .moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y)
        .strokeColor("#CCCCCC").stroke()
        .moveDown(0.3);
      inTable = false;
      continue;
    }

    // Table row — render as plain text row
    if (line.startsWith("|")) {
      if (!inTable) doc.moveDown(0.2);
      inTable = true;
      const cells = line.split("|").slice(1, -1).map((c) => c.trim());
      if (/^[-| ]+$/.test(line)) continue; // separator row
      doc.fontSize(9).font("Helvetica").fillColor("#333333")
        .text(cells.join("   "), { continued: false });
      continue;
    }

    inTable = false;

    // H1
    if (line.startsWith("# ")) {
      doc.moveDown(0.5).fontSize(16).font("Helvetica-Bold").fillColor("#1A1A2E")
        .text(line.slice(2));
      doc.moveDown(0.3);
      continue;
    }

    // H2
    if (line.startsWith("## ")) {
      doc.moveDown(0.5).fontSize(13).font("Helvetica-Bold").fillColor("#2C2F33")
        .text(line.slice(3));
      doc.moveTo(50, doc.y + 2).lineTo(doc.page.width - 50, doc.y + 2)
        .strokeColor("#DDDDDD").stroke();
      doc.moveDown(0.4);
      continue;
    }

    // H3
    if (line.startsWith("### ")) {
      doc.moveDown(0.3).fontSize(11).font("Helvetica-Bold").fillColor("#444444")
        .text(line.slice(4));
      doc.moveDown(0.2);
      continue;
    }

    // Bullet point
    if (/^[-*]\s/.test(line)) {
      const content = stripInlineMarkdown(line.slice(2).trim());
      doc.fontSize(10).font("Helvetica").fillColor("#222222")
        .text(`• ${content}`, { indent: 15 });
      continue;
    }

    // Blank line
    if (line === "") {
      doc.moveDown(0.3);
      continue;
    }

    // Regular paragraph
    const rendered = stripInlineMarkdown(line);
    doc.fontSize(10).font("Helvetica").fillColor("#222222").text(rendered);
  }
}

// Strip **bold** and _italic_ markers for plain rendering
function stripInlineMarkdown(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/`(.*?)`/g, "$1");
}
